# secret-slack-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
type: Opaque
stringData:
  slack-webhook-url: "https://hooks.slack.com/services/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"